application: banacekmusic
version: 1
runtime: python
api_version: 1

default_expiration: "24h"

handlers:

- url: /remotemedia/addComments
  script: /mediasearch/start.py

- url: /remotemedia/google/searchUrl
  script: /mediasearch/start.py
- url: /remotemedia/google/addBadMedia
  script: /mediasearch/start.py
- url: /remotemedia/google/getIgnoredSites
  script: /mediasearch/start.py
  
- url: /remotemedia/(.*\.(gif|png|jpg|js))
  static_files: remotemedia/\1
  upload: remotemedia/(.*\.(gif|png|jpg|js))
  
- url: /remotemedia/googlemediasearch.*
  static_files: remotemedia/GoogleMediaSearch.html
  upload: remotemedia/(GoogleMediaSearch.html)