application: banacekmusic
version: 1
runtime: python
api_version: 1

default_expiration: "24h"

handlers:

- url: /getSupportedApps
  script: /mediasearch/start.py
  
- url: /winamp.css
  script: /mediasearch/start.py

- url: /addComments
  script: /mediasearch/start.py

- url: /google/searchUrl
  script: /mediasearch/start.py
- url: /google/addBadMedia
  script: /mediasearch/start.py
- url: /google/getIgnoredSites
  script: /mediasearch/start.py
  
- url: /youtube/getVideo
  script: /mediasearch/start.py
  
- url: /(.*\.(gif|png|jpg|js))
  static_files: \1
  upload: (.*\.(gif|png|jpg|js))
  
- url: /googlemediasearch.*
  static_files: html/GoogleMediaSearch.html
  upload: html/(GoogleMediaSearch.html)
  
- url: /youtubesearch.*
  static_files: html/YouTubeSearch.html
  upload: html/(YouTubeSearch.html)
  
- url: /*.*
  static_files: html/WebMedia.html
  upload: html/(WebMedia.html)